### ISSUE TITLE
how you implemented this with react-dropzone?

### ISSUE THREAD

**Issue by Deboracgs** [manoj-makkuboy/fix-image-rotation#4]
Hello,

You have any example how you implemented this fix with react-dropzone  for iOS?

**Comment by manoj-makkuboy** [comment]
Hey @Deboracgs 
I don't have examples as of now but it goes like onDrop of react-dropzone would get a parameter of the image blob. Just pass the image blob to this library wrapped up in an array.

**Comment by Deboracgs** [comment]
ok, thanks 💃

**Comment by Deboracgs** [comment]
https://codepen.io/deboracgs/pen/GeXrpY

you can help me  ? @manoj-makkuboy

**Comment by manoj-makkuboy** [comment]
Can you try to use the library this way.
`let fixRotation = require('fix-image-rotation')     
   
   process = async (file) => {
         let orientationCorrectedFileArray = await fixRotation.fixRotation([file])
         let orientationCorrectedFile = orientationCorrectedFileArray[0]
      };`

Now orientationCorrectedFile should be having the corrected image.
